"""change user model

Revision ID: 5e798a1fbe44
Revises: 8f0e3eb7b19b
Create Date: 2025-03-28 11:25:29.818675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e798a1fbe44'
down_revision: Union[str, None] = '8f0e3eb7b19b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('user', 'mobile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
