"""change ticket history

Revision ID: 65d21b1e1101
Revises: fb4bf4d6c997
Create Date: 2025-04-02 16:23:30.748709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '65d21b1e1101'
down_revision: Union[str, None] = 'fb4bf4d6c997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attachment_ibfk_1', 'attachment', type_='foreignkey')
    op.drop_column('attachment', 'ticket_id')
    op.add_column('ticket', sa.Column('handler', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.alter_column('ticket', 'fault_reason',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('ticket', 'handling_method',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.add_column('tickethistory', sa.Column('original_data', sa.Text(), nullable=False))
    op.add_column('tickethistory', sa.Column('modified_data', sa.Text(), nullable=False))
    op.drop_column('tickethistory', 'fault_phenomenon')
    op.drop_column('tickethistory', 'handling_method')
    op.drop_column('tickethistory', 'change_notes')
    op.drop_column('tickethistory', 'fault_reason')
    op.drop_column('tickethistory', 'customer')
    op.drop_column('tickethistory', 'device_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickethistory', sa.Column('device_model', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('tickethistory', sa.Column('customer', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('tickethistory', sa.Column('fault_reason', mysql.TEXT(), nullable=False))
    op.add_column('tickethistory', sa.Column('change_notes', mysql.TEXT(), nullable=False))
    op.add_column('tickethistory', sa.Column('handling_method', mysql.TEXT(), nullable=False))
    op.add_column('tickethistory', sa.Column('fault_phenomenon', mysql.TEXT(), nullable=False))
    op.drop_column('tickethistory', 'modified_data')
    op.drop_column('tickethistory', 'original_data')
    op.alter_column('ticket', 'handling_method',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('ticket', 'fault_reason',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('ticket', 'handler')
    op.add_column('attachment', sa.Column('ticket_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('attachment_ibfk_1', 'attachment', 'ticket', ['ticket_id'], ['id'])
    # ### end Alembic commands ###
