"""change user model

Revision ID: fb4bf4d6c997
Revises: c81a1eef74ee
Create Date: 2025-04-01 09:28:29.922965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb4bf4d6c997'
down_revision: Union[str, None] = 'c81a1eef74ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=11),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=200),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('user', 'phone',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=11),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('user', 'updated_at')
    # ### end Alembic commands ###
